### ISSUE TITLE
⚡️ Einundzwandzig ₿itcoin Meetup Ruhrgebiet ⚡️

### ISSUE THREAD

**Issue by Veintiuno-21** [Einundzwanzig-Podcast/einundzwanzig.space#15]
https://t.me/Einundzwanzig_Ruhrgebiet

**Comment by dennisreimann** [comment]
Danke! Welche Städte soll das Meetup in etwa umfassen?

**Comment by Veintiuno-21** [comment]
Aktiv sind wir jetzt in Essen und Mülheim. 
In Essen  würde auch das Meetup stattfinden.

**Comment by dennisreimann** [comment]
Alles klar, ist nun dabei!
