### ISSUE TITLE
Change coordinate system in meetups.json

### ISSUE THREAD

**Issue by Mathias-U1F596** [Einundzwanzig-Podcast/einundzwanzig.space#153]
In the file meetups.json the coordinates of the meetup locations are (top, left) with respect to the map in the file dach.svg. Instead the coordinates should be specified by (latitude, longitude) which makes it much easier to add new meetups and also more precise. Additionally that would add flexibility for zooming and moving maps.

**Comment by dennisreimann** [comment]
Werden wir machen. Der Plan ist diese Daten zukünftig im Portal zu pflegen und über die [API](https://portal.einundzwanzig.space/api/meetups) abzurufen. Dort sind lat/long schon hinterlegt.

**Comment by dennisreimann** [comment]
Ist gemacht, siehe #155
