### ISSUE TITLE
fix: cname github pages for linz

### ISSUE THREAD

**Issue by dni** [Einundzwanzig-Podcast/einundzwanzig.space#177]
hiho! @dennisreimann 

irgendwie ist github pages fuer https://linz.einundzwanzig.space kaputt geworden und github will jetzt noch nen extra DNS eintrag. kannst das vl. machen :)? komisch normalerweilse reicht mir immer der CNAME alleine.

```
_github-pages-challenge-dni.linz.einundzwanzig.space TXT c77eb4f8e3aa58a79db6058e59fccc
```

![screenshot-1704460193](https://github.com/Einundzwanzig-Podcast/einundzwanzig.space/assets/1743657/f00b03ca-1ceb-43c9-8a5e-664e6c4b3ae6)

![screenshot-1704460294](https://github.com/Einundzwanzig-Podcast/einundzwanzig.space/assets/1743657/ff454c02-e414-4ee2-b34f-2fd655d4c381)

**Comment by dennisreimann** [comment]
Hey, habe ich hinzugefügt!
