### ISSUE TITLE
LICENSE.md missing

### ISSUE THREAD

**Issue by renepickhardt** [Einundzwanzig-Podcast/einundzwanzig.space#68]
Ich konnte nicht herausfinden, was die Lizenz in diesem Projekt ist. Entsprechend eurer Statuten ( https://einundzwanzig.space/files/EINUNDZWANZIG-Statuten.pdf ) hätte ich eine offene MIT oder Apache Lizenz erwartet.

**Comment by PatrickZGW** [comment]
Hi Rene, ja das hatten wir denke ich eh geplant, damit unsere anderen Einundzwanzig "Forks" die Website nutzen könnten. Eventuell sollten wir es sogar noch einfacher machen die Seite zu klonen, weil alles gerade auf Deutsch ist.
