### ISSUE TITLE
Beschreibung für meetups.json Pull-Reqest mit linux CMD

### ISSUE THREAD

**Issue by pjw65** [Einundzwanzig-Podcast/einundzwanzig.space#85]
Vermisse die Beschreibung, wie ein Pull-request für die Meetups unter Linux gemacht werden muss.
Habe jetzt mühsam alles selber herausgefunden.
Vielleicht könnte man das irgendwo ablegen und referenzieren:

1. gh installieren (nicht von snap), siehe https://github.com/cli/cli/blob/trunk/docs/install_linux.md
2. gpg2 installieren und öffentlichen Schlüssel zur Email generieren, falls noch nicht vorhanden (wird für das signieren benötigt)
3. folgendes ausführen
```
gh repo clone Einundzwanzig-Podcast/einundzwanzig.space
cd einundzwanzig.space/
git checkout -b ORTSNAME

```
4. edit content/meetups.json
5. folgendes eingeben
```
git add content/meetups.json
gh status
git commit -S -m "ORTSNAME"
gh pr create
```
3x <Enter>, um defaults zu übernehmen.

**Comment by dennisreimann** [comment]
Die Meetups werden mittlerweile über das [Portal](https://portal.einundzwanzig.space) gepflegt.
